vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix: '%product_images%'
            upload_destination: '%kernel.project_dir%/public%product_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            delete_on_update: false
            delete_on_remove: false
        header_images:
            uri_prefix: '%header_images%'
            upload_destination: '%kernel.project_dir%/public%header_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer


            delete_on_update: false
            delete_on_remove: false

